# Generated by Django 3.0.8 on 2020-07-13 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bitmex_id",
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
